### ISSUE TITLE
Skripte aktualisieren

### ISSUE THREAD

**Issue by TB-archIT** [opsi4instituts/dfn_putty#1]
Bitte die Skripte in github aktualisieren, so dass sie dem Paket im DFN-Repository (0.65-3) entsprechen.

**Comment by opsi-archIT-KIT** [comment]
Ich meinte https://github.com/opsi4instituts/dfn_putty sollte dem aktuellen Stand entsprechen.

**Comment by TB-archIT** [comment]
Ich meinte https://github.com/opsi4instituts/dfn_putty sollte dem aktuellen Stand entsprechen.

**Comment by iphtjena** [comment]
Ich habe die Aktuellen Files hochgeladen und somit müsste es dem aktuellen Stand entsprechen.

**Comment by TB-archIT** [comment]
Du verstehst mich falsch: unter https://github.com/opsi4instituts/dfn_putty ist die letzte Aktualisierung vom 15.07.15!

**Comment by iphtjena** [comment]
sorry tut mir leid ich weiss wirklich nicht was noch hochgeladen werden soll, bei mir wird angezeigt seit 20 h neuer Code

**Comment by TB-archIT** [comment]
Ok, jetzt sehe ich es auch. ?!? Verstehe ich nicht wirklich aber gut....
